# Generated by Django 6.0.3 on 2026-04-07 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_radius",
                    models.IntegerField(
                        default=100, help_text="Radius in meters for HR punch-in"
                    ),
                ),
                ("status", models.CharField(default="Enabled", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("meta", "Meta Ads"),
                            ("google", "Google Ads"),
                            ("website", "Website Form"),
                            ("social", "Social Media (Organic)"),
                            ("campaign", "Campaign"),
                            ("referral", "Referral"),
                            ("walkin", "Walk-in"),
                            ("whatsapp", "WhatsApp Inbound"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ad_set", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ad_creative",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("landing_page_url", models.URLField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("plot", "Plot"),
                            ("commercial", "Commercial"),
                            ("studio", "Studio"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "property_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bhk_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1bhk", "1 BHK"),
                            ("2bhk", "2 BHK"),
                            ("3bhk", "3 BHK"),
                            ("4bhk+", "4 BHK+"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("investment", "Investment"),
                            ("selfuse", "Self Use"),
                            ("rental", "Rental"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immediate", "Immediate"),
                            ("3months", "Within 3 Months"),
                            ("6months", "Within 6 Months"),
                            ("1year", "1 Year+"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "readiness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ready", "Ready to Move"),
                            ("underconstruction", "Under Construction"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="cold",
                        max_length=10,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("interested", "Interested"),
                            ("site_visit", "Site Visit"),
                            ("negotiation", "Negotiation"),
                            ("closed", "Closed"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="Enabled", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("missed", "Missed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "call_duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                (
                    "call_outcome",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("callback", "Callback Requested"),
                            ("not_answered", "Not Answered"),
                            ("converted", "Converted"),
                            ("site_visit", "Site Visit Scheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("call_notes", models.TextField(blank=True, null=True)),
                ("next_followup_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="Enabled", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.branch",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="dash.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("manager", "Branch Manager"),
                            ("tl", "Team Leader"),
                            ("member", "Call Team Member"),
                            ("hr", "HR Panel"),
                            ("marketing", "Marketing Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("status", models.CharField(default="Enabled", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.branch",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_members",
                        to="dash.userprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_leads",
                to="dash.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followup_at", models.DateTimeField()),
                (
                    "followup_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("site_visit", "Site Visit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "followup_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("rescheduled", "Rescheduled"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="Enabled", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.branch",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="dash.lead",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallWrapUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_outcome",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("callback", "Callback Requested"),
                            ("not_answered", "Not Answered"),
                            ("converted", "Converted"),
                            ("site_visit", "Site Visit Scheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "call_duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                ("detailed_notes", models.TextField(blank=True, null=True)),
                (
                    "temperature_update",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        max_length=10,
                    ),
                ),
                (
                    "stage_update",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("interested", "Interested"),
                            ("site_visit", "Site Visit"),
                            ("negotiation", "Negotiation"),
                            ("closed", "Closed"),
                            ("lost", "Lost"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "next_action",
                    models.CharField(
                        choices=[
                            ("followup", "Follow-up"),
                            ("site_visit", "Site Visit"),
                            ("send_details", "Send Details"),
                            ("close", "Close Deal"),
                            ("no_action", "No Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("followup_at", models.DateTimeField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("plot", "Plot"),
                            ("commercial", "Commercial"),
                            ("studio", "Studio"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "property_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="Enabled", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrapup",
                        to="dash.calllog",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrapups",
                        to="dash.lead",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="calllog",
            name="called_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_logs",
                to="dash.userprofile",
            ),
        ),
    ]
