# Generated by Django 6.0.3 on 2026-04-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dash", "0002_attendance_leaverequest_payroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="assigned_to_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_leads",
                to="dash.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_to_tl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tl_leads",
                to="dash.userprofile",
            ),
        ),
    ]
