# Generated by Django 5.2.13 on 2026-04-12 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0003_lead_assigned_to_manager_lead_assigned_to_tl"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="assigned_to_manager",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="assigned_to_tl",
        ),
        migrations.AddField(
            model_name="lead",
            name="gclid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="callwrapup",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("plot", "Plot"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="callwrapup",
            name="stage_update",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("closed", "Closed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="callwrapup",
            name="temperature_update",
            field=models.CharField(
                choices=[("cold", "Cold"), ("warm", "Warm"), ("hot", "Hot")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="bhk_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1bhk", "1 BHK"),
                    ("2bhk", "2 BHK"),
                    ("3bhk", "3 BHK"),
                    ("4bhk+", "4+ BHK"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("plot", "Plot"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[("investment", "Investment"), ("self_use", "Self Use")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="readiness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("just_looking", "Just Looking"),
                    ("interested", "Interested"),
                    ("ready", "Ready to Buy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("excel", "Excel"),
                    ("meta", "Meta Ads"),
                    ("google", "Google Ads"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="temperature",
            field=models.CharField(
                choices=[("cold", "Cold"), ("warm", "Warm"), ("hot", "Hot")],
                default="cold",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("immediate", "Immediate"),
                    ("3_months", "Within 3 Months"),
                    ("6_months", "Within 6 Months"),
                    ("later", "Later"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("tl", "Team Leader"),
                    ("employee", "Employee"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="LeadAssignmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_by_role", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_from_history",
                        to="dash.userprofile",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_to_history",
                        to="dash.userprofile",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dash.lead"
                    ),
                ),
            ],
        ),
    ]
