# Generated by Django 6.0.3 on 2026-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dash", "0005_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="google_adgroup_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="google_campaign_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_ad_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_adset_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="meta_campaign_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
